### ISSUE TITLE
I change data source include multi classes,but it's not work  'IndexError: Target 3 is out of bounds.'

### ISSUE THREAD

**Issue by lanteng77** [Ailln/image-classification#2]
i have no idea

**Comment by Ailln** [comment]
try to change the class config in datas/class_to_idx.json

**Comment by lanteng77** [comment]
i wana to train  model have [serven] classes,  I don't know how to modify，Can you be more detailed？I just want to add a few more classes.

**Comment by Ailln** [comment]
u can compare the content in that file. (if you dont understand the process, it is difficult to run.

**Comment by lanteng77** [comment]
thx, it work now.
